title: Murphy's dev portfolio
name: Tae Kyeong Lee
email: murphytklee@gmail.com
description: >-
  Web Developer & Java Back-End 


baseurl: ""
url: "https://murphytklee.github.io/"


# profile 이미지
profile_image: images/about2.jpg


# SNS 아이디
github_id: murphytklee


# Custom Color
primary: 0B0719 #메인 폰트 컬러 
primary_hover: 44A4F2 #메인 버튼색 
color_1: 2c98f0 #bar1
color_2: ec5453 #bar2
color_3: f9bf3f #bar3
color_4: a84cb8 #bar4 
color_5: 2fa499 #bar5
color_6: e88bd7 #bar6


# slider type 0  (텍스트가 우측 정렬된 슬라이더)
slider_0: # 형식에 맞추어 항목 추가
- background_url: images/home1.jpg
  # title:  Welcome !
  subtitle: Thank you for visiting my portfolio
  position: absolute
  transform: translate (-30%, -30%)
  left: 100px;
  bottom: 100px;
  

# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
- background_url: images/home5.jpg
  title: Web <br> Developer
  subtitle: >- 
    Java <br>
    Spring Framework <br>
    JPA / QueryDSL <br>
    html / css / js <br>
    MySQL / MongoDB <br>
    AWS / Docker / Kafka <br>
  position: absolute
  transform: translate (-50%, -50%)
  left: 0px;
  bottom: 0px;
  
    


# About
about_meta: About Me
about_header: >- 
  "Constant Challenges, Immersion, And Passion"
# about_introduce: >-
  
about_content: >-
  <ul>
    <li><strong>몰입하여 성취하는 개발자로 성장하겠습니다.</strong> League of Legends 프로게이머로 활동했던 경험이 있는 만큼 한 가지 일에 몰입하면 끈기와 노력 끝에 꼭 성취하는 성격입니다.</li>
    <li><strong>근거있는 의사결정을 하려고 노력합니다.</strong> 더 효율적인 시스템을 위해 기술을 도입하거나 아키텍처를 고민할 때 타당한 이유와 결과에 대해 깊이 고민합니다.</li>
    <li><strong>타협, 협동, 소통을 중요시 합니다.</strong> 팀원 한명 한명이 같은 목표와 생각을 가지고 움직여야 최상의 결과를 낼 수 있다고 생각합니다. 배움의 자세로 경청하고 적극적으로 의견을 전달하며 소통합니다.</li>
  </ul>

# about_services: # 형식에 맞추어 항목 추가
# - icon: icon-code
#   name: Java
# - icon: icon-data
#   name: Server
# - icon: icon-monitor
#   name: Web
# - icon: icon-phone3
#   name: App

# about_box_content: 괜찮은 문구 <br>박스 색바꾸는 yml파일에 추가 <br><br><br>야물파일로 변환 <strong>의뢰</strong>의뢰
# about_box_button:
#  link: #
#  name: sample


# Tech  skill
tech_meta: TECH SKILLS
tech_header: "The Skills that I can do"
# tech_content: 저는 이런 것을 할 수 있습니다. 
tech_list: # 형식에 맞추어 항목 추가
- name: JAVA
  color: color-4
  animation: fadeInLeft
  percent: 60
  mark: 100
  content: JAVA 기초, 객제 지향 언어의 기본적인 문법에 대해 알고 있으며, 자료구조 및 알고리즘을 자바로 공부하였습니다.
- name: Spring Framwork
  color: color-2
  animation: fadeInRight
  percent: 50
  mark: 100
  content: Spring 웹 프로젝트를 통해 REST API / Spring Security / Spring Data JPA를 익혔습니다.
- name: AWS
  color: color-3
  animation: fadeInLeft
  percent: 40
  mark: 100
  content: AWS EC2(ubuntu), RDS, S3, CodeDeploy을 사용하여 서버를 배포할 수 있습니다. Linux 명령어를 다룰 수 있습니다.
- name: Docker
  color: color-1
  animation: fadeInRight
  percent: 50
  mark: 100
  content: Docker를 이용해 CI/CD 구축 및 Container Network, Docker File 구성에 익숙하며 Docker Swarm을 이용해 Container Orchestration을 활용한 경험이 있습니다.
- name: MySQL / MongoDB
  color: color-5
  animation: fadeInRight
  percent: 60
  mark: 100
  content: MySQL의 기본 쿼리문을 활용하여 원하는 데이터를 추출할 수 있습니다. MongoDB Atlas를 사용해 NoSQL Database를 구축한 경험이 있습니다.
- name: Kafka
  color: none
  animation: fadeInRight
  percent: 30
  mark: 100
  content: STOMP 시스템의 메세지 큐로 Kafka와 sink connect를 활용해 비동기적인 데이터 파이프라인을 구축했습니다.


# Project
project_meta: My Work
project_header: PROJECT
project_introduce: 
#project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다.    # 더보기 내용
# project_load_more_url: #
# project_desc: 앞으로 더 많은 프로젝트가 추가될 예정입니다. 
# project_my_name: 개인 프로젝트

# project_my: # 형식에 맞추어 항목 추가
# - background_url: images/spring.png
#   animation: fadeInLeft
#   name: Spring WEB site
#   description: Spring Framework를 활용한 웹사이트 제작 프로젝트 입니다.
#   detail_url: #
#   readmore_url: #

# - background_url: images/gitblog.png
#   animation: fadeInLeft
#   name: DEV githib blog
#   description: 깃 블로그를 직접 개발하여 배운 것들을 꾸준히 기록하며 배움을 나눕니다. 
#   detail_url: https://hyesue-lee.github.io/
#   readmore_url: #

# project_team_name: 팀 프로젝트
project_team: # 형식에 맞추어 항목 추가
- background_url: images/team_project1.PNG
  animation: fadeInRight
  name: "2023.05.19 ~ 2023.06.30 (6주) | BE: 4명, FE: 2명"
  description: "<strong>\"this.code\"</strong> <br> 실시간 채팅 서비스에서 발생하는 대규모 트래픽 처리를 위한 성능 개선"
  github_url: https://github.com/murphytklee/chat-challenge-BE
  readmore_url: https://www.notion.so/this-code-17-7ac95cdad44342be8b2a1ca0a4098bb6?pvs=4
  what_i_did:  pdf/this_code.pdf


- background_url: images/team_project2.PNG
  animation: fadeInRight
  name: "2023.05.12 ~ 2023.05.18 (1주) | BE: 4명, FE: 2명"
  description: "<strong>\"Airbnb Clone Coding\"</strong> <br> 프론트 협업 및 예약 시스템 구현 경험을 위한 Airbnb 클론 코딩 프로젝트"
  github_url: https://github.com/taekk1a2a3a/CloneCoding5_BE
  readmore_url: #
  what_i_did: pdf/airbnb_clone.pdf

- background_url: images/team_project3.PNG
  animation: fadeInRight
  name: "2023.05.05 ~ 2023.05.11 (1주) | BE: 4명, FE: 2명"
  description: "<strong>\"내가 짤명왕\"</strong> <br> 짤 이미지를 게시물에 업로드 한 후, 그 짤에 가장 어울리는 제목을 뽑는 웹서비스"
  github_url: https://github.com/taekk1a2a3a/meme_nameking_BE
  readmore_url: #
  what_i_did: pdf/name_king.pdf

project_business_name: Business
project_business: # 형식에 맞추어 항목 추가
- background_url: images/my_business.PNG
  animation: fadeInTop
  name: 인프런강의(2021~)
  description: >-
    취준과 대학원진학을 동시에 했을때 많은 곳에서 github 주소뿐만아니라 개발 블로그주소도 요청하는데가 많았다.(물론 필수는 아니였지만) 
    또한 교육기관(멋쟁이사자처럼,네이버 부스트 캠프, 소마등)에서도 마찬가지이다. 현재 프로그래밍의 중요도가 올라가고있으며 초등학생부터 의무교육을 시작한다고 한다. 
    많은 비전공자들이 뒤늦게 프로그래밍을 시작하고 있다. 열심히 배우고 지원할려니 개발 블로그를 요청한다... 프로그래밍을 시작할때 알았다면 얼마나 좋았을까. 
    공부하면서 블로그 내용을 채웠으면 참 좋았을것이다. 이런 흐름을 캐치하여 나는 개발자다운 블로그인 깃헙블로그를 만드는 짧은 강의를 만들었다. 
  detail_url: #
  readmore_url: #


# Experience
exp_meta: What have I achieved?
exp_header: Other Experience
# exp_content: 기술력 외에도 이러한 역량을 겸비하고 있습니다. 
exp_services: # 형식에 맞추어 항목 추가
- name: 커뮤니케이션 
  color: color-4
  icon: icon-speech-bubble
  content: 해외경험, 성장력, 소통력, 책임감
- name: 성장 가능성
  color: color-2
  icon: icon-lightbulb
  content: 기술력 외에도 이러한 역량을 겸비하고 있습니다. 기술력 외에도 이러한 역량을 겸비하고 있습니다. 기술력 외에도 이러한 역량을 겸비하고 있습니다. 
- name: 책임감 
  color: color-3
  icon: icon-book
  content: 기술력 외에도 이러한 역량을 겸비하고 있습니다. 기술력 외에도 이러한 역량을 겸비하고 있습니다. 기술력 외에도 이러한 역량을 겸비하고 있습니다. 
exp_counters:
- name: Subscribers
  count: 3000
  speed: 5000
- name: project
  count: 6
  speed: 5000


# Career
carerr_meta: career
career_header: Work Career
career_list:
- name: Capstone Design
  date: 2022.08 ~ 2022.12 (4개월)
  content: >-
    <ul>
      <li>
        <strong>센서, 엑츄에이터와 아두이노(C/C++)를 연결해 자동으로 제어되는 스마트 팜 시스템 개발</strong>
      </li>
      <li>
        <strong>블루투스 모듈, 앱 인벤터를 이용해 스마트폰에서 모니터링 및 제어 기능 개발</strong>
      </li>
      <li>
        <strong>학술제 입상</strong>
      </li>
    </ul>
  color: 
  icon: icon-pen2
  animation: fadeInLeft
- name: Internship
  date: (주) 시스인 2018.07 ~ 2018.08 (1개월)
  content: >-
    <ul>
      <li>
        <strong>모터 컨트롤 테스트 프로그램 개발</strong>
      </li>
      <li>
        <strong>마이크로스테이지 성능 실험 및 검증,이동경로 및 패턴 명령 분석</strong>
      </li>
      <li>
        <strong>Visual Studio의 Windows Forms(C#)을 사용하여 모터 컨트롤 프로그램 기획, 설계, 개발</strong>
      </li>
    </ul>
  color: 
  icon: icon-pen2
  animation: fadeInLeft
- name: Barista
  date: 카페 바리스타 (4년)
  content: >-
    <ul>
      <li>
        2023.11 ~ 2024.05 <strong>Coffee 101 Street</strong>
      </li>
      <li>
        2021.02 ~ 2023.03 <strong>메가커피</strong>
      </li>
      <li>
        2020.07 ~ 2021.01 <strong>DailyTea</strong>
      </li>
      <li>
        2017.05 ~ 2017.11  <strong>델라보보</strong>
      </li>
      <li>
        2015.06 ~ 2016.01 <strong>browny 70</strong>
      </li>
    </ul>
  color: 
  icon: icon-pen2
  animation: fadeInRight
- name: Progamer
  date: League of Legends 프로게이머 (1년)
  content: >-
    <ul>
      <li>
        2015.01 ~ 2015.03 <strong>Hong Kong Esports, 대만</strong>
      </li>
      <li>
        2014.11 ~ 2015.01 <strong>Prime ITENJOY, 한국</strong>
      </li>
      <li>
        2014.05 ~ 2014.11 <strong>Incredible Miracle, 한국</strong>
      </li>
    </ul>
  color: 
  icon: icon-pen2
  animation: fadeInRight


# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: Boot Camp
  subtitle: 항해99
  date: 2023.03 - 2023.07
  content: 웹 개발 백엔드 과정 수료 (Java, Spring)
- title: University
  contents:
    - subtitle: 단국대학교 산업공학과 수석 졸업
      date: 2021.03 - 2023.02
      content: 
    - subtitle: 호서대학교 기계공학과 중퇴
      date: 2018.03 - 2020.02
      content: 
- title: Certificate
  subtitle: TOEIC SPEAKING 140 / IH
  date: 2024.02.25 ~




# Blog
blog_meta: self-improvement
blog_header: Channel
blog_load_more: 더 발전하기 위해 항상 노력합니다    # 더보기 내용
blog_load_more_url: #
blog_list:
- title: GitHub
  # subtitle: 
  # date: 
  # content: 알고리즘, 프로젝트 및 개발 공부와 관련된 결과물들을 꾸준히 커밋하고 있습니다.
  thumbnail_url: images/github2.png
  link: https://github.com/murphytklee
- title: Velog
  # subtitle: 
  # date: 
  # content: 
  thumbnail_url: images/velog.png
  link: https://velog.io/@murphytklee/posts


# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: murphytklee@gmail.com
  icon: icon-mail
- title: 서울특별시 강서구
  icon: icon-map

contact_message: <em>연락해주셔서 감사합니다.</em> 24시간이내에 회신드리도록 하겠습니다. :)


optional_front_matter:
  remove_originals:    true
