title: Murphy's dev portfolio
name: Tae Kyeong Lee
email: murphytklee@gmail.com
description: >-
  Web Developer & Java Back-End 


baseurl: ""
url: "https://murphytklee.github.io/"


# profile 이미지
profile_image: images/about.jpg


# SNS 아이디
github_id: murphytklee


# Custom Color
primary: 0B0719 #메인 폰트 컬러 
primary_hover: 44A4F2 #메인 버튼색 
color_1: 2c98f0 #bar1
color_2: ec5453 #bar2
color_3: f9bf3f #bar3
color_4: a84cb8 #bar4 
color_5: 2fa499 #bar5
color_6: e88bd7 #bar6


# slider type 0  (텍스트가 우측 정렬된 슬라이더)
slider_0: # 형식에 맞추어 항목 추가
- background_url: images/home1.jpg
  title:  Welcome <br> To my <br> Portfolio
  position: absolute
  transform: translate (-30%, -30%)
  left: 100px;
  bottom: 100px;


# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
- background_url: images/home2.jpg
  title: JAVA Web <br> Backend Developer
  subtitle: >- 
    JAVA <br>
    Spring Framework <br>
    JPA / QueryDSL <br>
    html / css / js <br>
    MySQL / mongoDB <br>
    AWS / Docker / Kafka <br>
  position: absolute
  transform: translate (-50%, -50%)
  left: 0px;
  bottom: 0px;
  
    


# About
about_meta: About Me
about_header: >- 
  "Constant Challenges, Immersion, And Passion"
# about_introduce: >-
  
about_content: >-
  <ul>
    <li><strong>몰입하여 성취하는 개발자로 성장하겠습니다.</strong> League of Legends 프로게이머로 활동했던 경험이 있는 만큼 한 가지 일에 몰입하면 끈기와 노력 끝에 꼭 성취하는 성격입니다.</li>
    <li><strong>근거있는 의사결정을 하려고 노력합니다.</strong> 더 효율적인 시스템을 위해 기술을 도입하거나 아키텍처를 고민할 때 타당한 이유와 결과에 대해 깊이 고민합니다.</li>
    <li><strong>타협, 협동, 소통을 중요시 합니다.</strong> 팀원 한명 한명이 같은 목표와 생각을 가지고 움직여야 최상의 결과를 낼 수 있다고 생각합니다. 배움의 자세로 경청하고 적극적으로 의견을 전달하며 소통합니다.</li>
  </ul>

# about_services: # 형식에 맞추어 항목 추가
# - icon: icon-code
#   name: Java
# - icon: icon-data
#   name: Server
# - icon: icon-monitor
#   name: Web
# - icon: icon-phone3
#   name: App

# about_box_content: 괜찮은 문구 <br>박스 색바꾸는 yml파일에 추가 <br><br><br>야물파일로 변환 <strong>의뢰</strong>의뢰
# about_box_button:
#  link: #
#  name: sample


# Tech  skill
tech_meta: TECH SKILLS
tech_header: "The Skills that I can do"
# tech_content: 저는 이런 것을 할 수 있습니다. 
tech_list: # 형식에 맞추어 항목 추가
- name: JAVA
  color: color-4
  animation: fadeInLeft
  percent: 60
  mark: 60
  content: JAVA 기초, 객제 지향 언어의 기본적인 문법에 대해 알고 있으며, 자료구조 및 알고리즘을 자바로 공부하였습니다.
- name: Spring Framwork
  color: color-2
  animation: fadeInRight
  percent: 50
  mark: 50
  content: Spring 웹 프로젝트를 통해 REST API / Spring Security / Spring Data JPA를 익혔습니다.
- name: AWS
  color: color-3
  animation: fadeInLeft
  percent: 40
  mark: 40
  content: AWS EC2(ubuntu), RDS, S3, CodeDeploy을 사용하여 서버를 배포할 수 있습니다. Linux 명령어를 다룰 수 있습니다.
- name: Docker
  color: color-1
  animation: fadeInRight
  percent: 50
  mark: 50
  content: Docker를 이용해 CI/CD 구축 및 Container Network, Docker File 구성에 익숙하며 Docker Swarm을 이용해 Container Orchestration을 활용한 경험이 있습니다.
- name: MySQL / MongoDB
  color: color-5
  animation: fadeInRight
  percent: 60
  mark: 60
  content: MySQL의 기본 쿼리문을 활용하여 원하는 데이터를 추출할 수 있습니다. MongoDB Atlas를 사용해 NoSQL Database를 구축한 경험이 있습니다.
- name: Kafka
  color: none
  animation: fadeInRight
  percent: 30
  mark: 30
  content: STOMP 시스템의 메세지 큐로 Kafka와 sink connect를 활용해 비동기적인 데이터 파이프라인을 구축했습니다.


# Project
project_meta: My Work
project_header: PROJECT
project_introduce: 
#project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다.    # 더보기 내용
project_load_more_url: #
project_desc: 앞으로 더 많은 프로젝트가 추가될 예정입니다. 
project_my_name: 개인 프로젝트

project_my: # 형식에 맞추어 항목 추가
- background_url: images/spring.png
  animation: fadeInLeft
  name: Spring WEB site
  description: Spring Framework를 활용한 웹사이트 제작 프로젝트 입니다.
  detail_url: #
  readmore_url: #

- background_url: images/gitblog.png
  animation: fadeInLeft
  name: DEV githib blog
  description: 깃 블로그를 직접 개발하여 배운 것들을 꾸준히 기록하며 배움을 나눕니다. 
  detail_url: https://hyesue-lee.github.io/
  readmore_url: #

project_team_name: 팀 프로젝트
project_team: # 형식에 맞추어 항목 추가
- background_url: images/personal_project1.PNG
  animation: fadeInRight
  name: 딥러닝 불량품 검출(2021.04)
  description: 공장에서 만들어내는 부품의 데이터를 통해 불량품을 검출하는 프로젝트입니다. 
  detail_url: #
  readmore_url: #

- background_url: images/team_project3.PNG
  animation: fadeInRight
  name: sasdasdasdsadsagjghkukt(2020.05)
  description: 2019년 드론기술발전에 따른 드론관련 사고들이 많아지고 있음을 파악하고 그에따른 대처가 필요하다고 생각 하여 인공지능을 이용한 Anti Drone Robot 을 개발하였습니다.
  detail_url: #
  readmore_url: #

project_business_name: Business
project_business: # 형식에 맞추어 항목 추가
- background_url: images/my_business.PNG
  animation: fadeInTop
  name: 인프런강의(2021~)
  description: >-
    취준과 대학원진학을 동시에 했을때 많은 곳에서 github 주소뿐만아니라 개발 블로그주소도 요청하는데가 많았다.(물론 필수는 아니였지만) 
    또한 교육기관(멋쟁이사자처럼,네이버 부스트 캠프, 소마등)에서도 마찬가지이다. 현재 프로그래밍의 중요도가 올라가고있으며 초등학생부터 의무교육을 시작한다고 한다. 
    많은 비전공자들이 뒤늦게 프로그래밍을 시작하고 있다. 열심히 배우고 지원할려니 개발 블로그를 요청한다... 프로그래밍을 시작할때 알았다면 얼마나 좋았을까. 
    공부하면서 블로그 내용을 채웠으면 참 좋았을것이다. 이런 흐름을 캐치하여 나는 개발자다운 블로그인 깃헙블로그를 만드는 짧은 강의를 만들었다. 
  detail_url: #
  readmore_url: #


# Experience
exp_meta: What have I achieved?
exp_header: What I Experienced
exp_content: 기술력 외에도 이러한 역량을 겸비하고 있습니다. 
exp_services: # 형식에 맞추어 항목 추가
- name: 소통력 
  color: color-2
  icon: icon-speech-bubble
  content: 개발은 협업으로 이루어지기에 소통 또한 중요하다고 생각합니다. 활발한 성격으로 소통에 능합니다.
- name: 습득력
  color: color-2
  icon: icon-lightbulb
  content: 다방면으로 호기심이 많아 탐구하는 습관으로 새로운 것을 만났을 때 빠르게 습득합니다. 
- name: 자기계발 
  color: color-3
  icon: icon-book
  content: 자기계발에 관심이 많습니다. 독서를 통해 인사이트를 얻고 꾸준한 운동으로 체력을 다지고 있습니다.
exp_counters:
- name: Subscribers
  count: 3000
  speed: 5000
- name: project
  count: 6
  speed: 5000


# Career
carerr_meta: career
career_header: Work Career
career_list:
- name: 금융IT 프리랜서    
  date: 2021.08~ 현재 
  content: 여신 재무비율 계산 시스템 개발 <br> 전문거래 EAI 통신 <br>... 
  color: color-2
  icon: icon-pen2
  animation: fadeInLeft
- name: 네트워크 솔루션
  date: 2019.03~2021.07
  content: 프로젝트 수행 및 커스터마이징 개발<br> Linux 환경의 솔루션 설치 및 구축 <br> 본인인증 연동 및 SSO / SMS API 연계 개발<br> 
           배치 프로그램 - 사용자 및 데이터 마이그레이션 개발 <br> 조직도 인사 DB 연계 개발  <br> ...   
  color: color-2
  icon: icon-pen2
  animation: fadeInLeft
- name: 개발 기획
  date: 2015.03~2016.11
  content: 정부 연구과제 참여 - 발전 설비현장 성능평가 프로그램 분석 및 설계 <br> ...
  color: color-2
  icon: icon-pen2
  animation: fadeInRight


# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: UNIVERSITY
  subtitle: xx대학교 xx과 졸업
  date: 20xx.03 - 20xx.02
  content: 대학생활 설명 ~~ 
- title:  HIGH SCHOOL
  subtitle: xx고등학교
  date: 20xx.03 - 20xx.02



# Blog
blog_meta: self-improvement
blog_header: BLOG and YOUTUBE
blog_load_more: 더 발전하기 위해 항상 노력합니다    # 더보기 내용
blog_load_more_url: #
blog_list:
- title: 깃허브 블로그 
  subtitle: 개발 블로그 운영
  date: 2021.11
  content: 깃 블로그를 직접 개발하여 배운 것들을 꾸준히 기록하며 배움을 나눕니다. 
  thumbnail_url: images/gitblog.png
  link: https://hyesue-lee.github.io/
- title: 유튜브 개발채널
  subtitle: 개발 컨텐츠 유튜브 채널 운영 [치얼스헤나]
  date: 2020.11
  content: 유튜브 채널을 운영하며 같은 분야의 다양한 사람들과 소통하고 있습니다. 
  thumbnail_url: images/youtube.png
  link: https://youtube.com/channel/UC6YIWKSsY_J7rMYfAb7_tOw
- title: 티스토리 블로그 
  subtitle: 이전 블로그
  date: 2018.03
  content: 2018년부터 꾸준히 기록하였던 티스토리 첫 블로그 입니다. 
  thumbnail_url: images/ti.png
  link: https://cheershennah.tistory.com/


# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: hyesue12@gmail.com
  icon: icon-globe-outline
- title: +82 10 xxxx xxxx
  icon: icon-phone
- title: 서울 특별시 마포구 
  icon: icon-map

contact_message: <em>연락해주셔서 감사합니다.</em> 24시간이내에 회신드리도록 하겠습니다. :)


optional_front_matter:
  remove_originals:    true
